from __future__ import annotations

import argparse
import csv
from pathlib import Path

import numpy as np


DEFAULT_METRICS = [
    "multi_ova_cam_pearson",
    "multi_ova_cam_spearman",
    "multi_ova_cam_mean_abs_diff",
    "multi_ova_cam_centroid_distance_norm",
    "multi_ova_cam_argmax_distance_norm",
    "multi_ova_cam_top5_iou",
    "multi_ova_cam_top10_iou",
    "multi_ova_cam_top15_iou",
    "multi_ova_cam_top20_iou",
    "multi_cam_active_area_frac_50",
    "ova_cam_active_area_frac_50",
    "multi_cam_active_area_frac_75",
    "ova_cam_active_area_frac_75",
    "multi_cam_gini",
    "ova_cam_gini",
]


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Aggregate TB Chest X-ray Grad-CAM Multi-vs-OVA similarity metrics "
            "from one or more gradcam_index.csv files."
        )
    )
    parser.add_argument(
        "--csv",
        type=Path,
        nargs="+",
        required=True,
        help="One or more gradcam_index.csv files generated by explicabilidad_gradcam_vgg.py.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("resultados_actualizados/analisis_explicabilidad/tb_multi_ova"),
    )
    return parser


def seed_from_path(path: Path) -> str:
    for part in path.parts:
        if part.startswith("seed_"):
            pieces = part.split("_")
            if len(pieces) >= 2 and pieces[1].isdigit():
                return pieces[1]
    return ""


def read_rows(paths: list[Path]) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for path in paths:
        with path.open(newline="") as handle:
            reader = csv.DictReader(handle)
            for row in reader:
                row = dict(row)
                row["source_csv"] = str(path)
                row["seed"] = row.get("seed") or seed_from_path(path)
                rows.append(row)
    if not rows:
        raise ValueError("No rows found in input CSV files")
    return rows


def as_float(row: dict[str, str], key: str) -> float | None:
    value = row.get(key, "")
    if value == "":
        return None
    try:
        return float(value)
    except ValueError:
        return None


def mean_std(values: list[float]) -> tuple[float | str, float | str]:
    if not values:
        return "", ""
    array = np.asarray(values, dtype=np.float64)
    return float(array.mean()), float(array.std(ddof=1)) if array.size > 1 else 0.0


def summarize(rows: list[dict[str, str]], group_keys: list[str], metrics: list[str]) -> list[dict[str, object]]:
    groups: dict[tuple[str, ...], list[dict[str, str]]] = {}
    for row in rows:
        key = tuple(row.get(group_key, "") for group_key in group_keys)
        groups.setdefault(key, []).append(row)

    summary_rows: list[dict[str, object]] = []
    for group_values, group_rows in sorted(groups.items()):
        summary: dict[str, object] = {"n": len(group_rows)}
        for group_key, group_value in zip(group_keys, group_values):
            summary[group_key] = group_value
        for metric in metrics:
            values = [
                value
                for row in group_rows
                for value in [as_float(row, metric)]
                if value is not None
            ]
            mean, std = mean_std(values)
            summary[f"{metric}_mean"] = mean
            summary[f"{metric}_std"] = std
        summary_rows.append(summary)
    return summary_rows


def add_delta_metrics(rows: list[dict[str, str]]) -> None:
    metric_pairs = [
        ("cam_active_area_frac_50", "area50_delta_ova_minus_multi"),
        ("cam_active_area_frac_75", "area75_delta_ova_minus_multi"),
        ("cam_gini", "gini_delta_ova_minus_multi"),
    ]
    for row in rows:
        for base_metric, output_key in metric_pairs:
            multi_value = as_float(row, f"multi_{base_metric}")
            ova_value = as_float(row, f"ova_{base_metric}")
            row[output_key] = "" if multi_value is None or ova_value is None else str(ova_value - multi_value)


def write_csv(path: Path, rows: list[dict[str, object]]) -> None:
    if not rows:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = sorted({key for row in rows for key in row.keys()})
    ordered = [
        key
        for key in ["seed", "true_label", "outcome", "cam_target_mode", "n"]
        if key in fieldnames
    ]
    fieldnames = ordered + [key for key in fieldnames if key not in ordered]
    with path.open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def main() -> None:
    args = build_parser().parse_args()
    rows = read_rows(args.csv)
    add_delta_metrics(rows)
    metrics = [
        metric
        for metric in DEFAULT_METRICS
        if any(row.get(metric, "") != "" for row in rows)
    ] + [
        "area50_delta_ova_minus_multi",
        "area75_delta_ova_minus_multi",
        "gini_delta_ova_minus_multi",
    ]

    write_csv(args.output_dir / "tb_gradcam_multi_ova_resumen_global.csv", summarize(rows, [], metrics))
    write_csv(args.output_dir / "tb_gradcam_multi_ova_resumen_por_semilla.csv", summarize(rows, ["seed"], metrics))
    write_csv(args.output_dir / "tb_gradcam_multi_ova_resumen_por_clase.csv", summarize(rows, ["true_label"], metrics))
    write_csv(args.output_dir / "tb_gradcam_multi_ova_resumen_por_outcome.csv", summarize(rows, ["outcome"], metrics))
    write_csv(
        args.output_dir / "tb_gradcam_multi_ova_resumen_semilla_clase.csv",
        summarize(rows, ["seed", "true_label"], metrics),
    )
    print(f"Read {len(rows)} rows from {len(args.csv)} CSV files")
    print(f"Output directory: {args.output_dir}")


if __name__ == "__main__":
    main()
